version: '3.8'
services:
  airline-db:
    container_name: airline-db
    hostname: airline-db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=airadmin
      - POSTGRES_DB=airlinedb
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432
    expose:
      - 5432
  airline-app:
    container_name: airline-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://airadmin:123123@airline-db/airlinedb
    depends_on:
      - airline-db