"""empty message

Revision ID: 7e02c4b3fe93
Revises: 
Create Date: 2022-04-30 20:56:13.582095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e02c4b3fe93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('departure_airport_code', sa.String(length=50), nullable=True),
    sa.Column('departure_airport_name', sa.String(length=50), nullable=True),
    sa.Column('departure_city', sa.String(length=50), nullable=True),
    sa.Column('departure_locale', sa.String(length=50), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('arrival_airport_code', sa.String(length=50), nullable=True),
    sa.Column('arrival_airport_name', sa.String(length=50), nullable=True),
    sa.Column('arrival_city', sa.String(length=50), nullable=True),
    sa.Column('arrival_locale', sa.String(length=50), nullable=True),
    sa.Column('ticket_price', sa.Integer(), nullable=True),
    sa.Column('ticket_currency', sa.String(length=50), nullable=True),
    sa.Column('flight_number', sa.Integer(), nullable=True),
    sa.Column('seat_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('outbound_flight_id', sa.Integer(), nullable=True),
    sa.Column('payment_token', sa.String(length=50), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('booking_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outbound_flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('flights')
    # ### end Alembic commands ###
